<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-26G0JUG" failures="14" tests="96" name="com.Reporting.tests.BalanceSheetTest" time="2560.153" errors="0" timestamp="2024-05-16T16:57:32 IST" skipped="0">
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateReportingBalanceSheetPageVisibility" time="27.878"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateReportingBalanceSheetPageTabs" time="3.761"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateBalanceSheetSummerySectionsVisibility" time="4.207"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateAssetAndLiabilitiesAmountVisibility" time="4.828"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateAssetAmountValue" time="3.805"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateLiabilitiesAmountValue" time="3.551"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateLoanAmountIsSumOfAllBorrowerLoanAmount" time="9.280"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateFacilitiesAmountIsSumOfAllFacilityAmount" time="8.532"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateValuesOnApplyingCustomSearchCalender" time="7.568"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateCustomSearchCalenderPopup" time="3.763"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateCustomFieldInitialSelectedDate" time="6.415"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateAppliedDateInCustomSearchField" time="6.032"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateCalendarClosedOnClickedOutside" time="19.064"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateCalendarMonthsOnClickSearchByMonth" time="19.186"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateCalendarYearByForwardAndBackwordArrow" time="4.373"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateUpdatedAmountsAfterSearchByMonth" time="23.112"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateAmountsWithoutSearchBySelectMonth" time="8.652"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateMonthCalendarClosedOnClickedOutside" time="35.033"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateLoanBalanceTableColumns" time="3.389"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateLoanBalanceAmountColumnDataSorting" time="13.233"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateLoanBalanceLoanRefColumnDataSorting" time="28.107">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at com.Reporting.tests.BalanceSheetTest.validateLoanBalanceLoanRefColumnDataSorting(BalanceSheetTest.java:1584)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- validateLoanBalanceLoanRefColumnDataSorting -->
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateLoanBalanceRefNameInLoanDatabase" time="137.185">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at com.Reporting.tests.BalanceSheetTest.validateLoanBalanceRefNameInLoanDatabase(BalanceSheetTest.java:1671)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- validateLoanBalanceRefNameInLoanDatabase -->
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateNavigateEditBridgeLoanPageFromLoanBalance" time="6.051"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateLoanRefNoInLoanDatabase" time="18.481"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateLoanBalanceAmountInLoanDatabase" time="31.137"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateAmountsWhenUserPerformLoanDisbursement" time="174.825"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateUpdatedDisbursedAmount" time="142.494">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at com.Reporting.tests.BalanceSheetTest.validateUpdatedDisbursedAmount(BalanceSheetTest.java:2060)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- validateUpdatedDisbursedAmount -->
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateFacilityBalanceTableColumnsVisibility" time="3.750"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateFacilityBalanceTableAscendingOrderDataSorting" time="20.191">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at com.Reporting.tests.BalanceSheetTest.validateFacilityBalanceTableAscendingOrderDataSorting(BalanceSheetTest.java:2204)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- validateFacilityBalanceTableAscendingOrderDataSorting -->
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateFacilityReferenceDataSorting" time="22.462">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at com.Reporting.tests.BalanceSheetTest.validateFacilityReferenceDataSorting(BalanceSheetTest.java:2252)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- validateFacilityReferenceDataSorting -->
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateInternalRefNoInLoanDatabase" time="159.464">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at com.Reporting.tests.BalanceSheetTest.validateInternalRefNoInLoanDatabase(BalanceSheetTest.java:2320)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- validateInternalRefNoInLoanDatabase -->
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateNavigationToEditLoanFacilitySummaryTab" time="36.844"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateFacilityRefNumber" time="32.313"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateNavigationToEditLoanFacilitySummaryPage" time="27.752"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateFacilityAmountInFundingDatabase" time="47.071"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateFacilityDisbursement" time="43.985">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at com.Reporting.tests.BalanceSheetTest.validateFacilityDisbursement(BalanceSheetTest.java:2719)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- validateFacilityDisbursement -->
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateBalanceSheetDetailsSectionsVisibility" time="6.385"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateAssetBalanceSectionAmountsVisibility" time="6.429"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateAssetBalanceAmount" time="8.875"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateAssetAndFacilitiesBalanceEqualAmount" time="8.828"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateCashBalanceSectionAmountsVisibility" time="6.696"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateCashBalanceSectionOpeningAmount" time="8.056"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateCashBalanceSectionClosingAmount" time="8.333"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateCashBalanceSectionLoanInAmount" time="8.470"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateCashBalanceSectionLoanOutAmount" time="8.168"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateCashBalanceSectionFacilitiesInAmount" time="8.018"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateCashBalanceSectionFacilitiesOutAmount" time="7.743"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateLoanBalanceTableColumnsVisibility" time="5.967"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateNavigationToNewLoanSummaryTab" time="8.482"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateLoanBlanceTableAscendingOrderDataSorting" time="27.708"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateLoanBlanceTableDescendingOrderDataSorting" time="112.364"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateDisbursementsAmountVisibility" time="20.977"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateRepaymentsAmountVisibility" time="20.560"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateClosingBalanceAmountVisibility" time="20.714"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateFacilityBalanceTableColumnVisibility" time="6.652"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateNavigationToFundingSummaryTab" time="23.818"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateFacilityBlanceTableAscendingOrderDataSorting" time="21.826"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateFacilityBlanceTableDescendingOrderDataSorting" time="34.737"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateDrawdownsAmountVisibility" time="22.852"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateFacilityTableRepaymentsAmountVisibility" time="21.527"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateFacilityTableClosingBalanceAmountVisibility" time="20.594"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateValuesUpdateBasedOnCustomDateRange" time="34.499">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at com.Reporting.tests.BalanceSheetTest.validateValuesUpdateBasedOnCustomDateRange(BalanceSheetTest.java:4956)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- validateValuesUpdateBasedOnCustomDateRange -->
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateCustomSearchStartAndEndDateCalendarPopup" time="23.039"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateDefaultDateIsCurrentDate" time="13.019"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateSelectStartAndEndDateFromCalendar" time="54.080"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateStartAndEndDateCalendarClose" time="7.115">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at com.Reporting.tests.BalanceSheetTest.validateStartAndEndDateCalendarClose(BalanceSheetTest.java:5364)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- validateStartAndEndDateCalendarClose -->
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateSearchByMonthCalendarMonths" time="20.997"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateSelectYearFromCalendarForSearchByMonth" time="21.988"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateCalendarYearByForwardAndBackwordArrows" time="22.154"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateUpdatedAmountsAfterSelectingSearchByMonths" time="27.224"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateAmountsNotUpdated" time="10.019"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateCalendarDatePickerClosedOnClickedOutside" time="5.894">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at com.Reporting.tests.BalanceSheetTest.validateCalendarDatePickerClosedOnClickedOutside(BalanceSheetTest.java:6070)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- validateCalendarDatePickerClosedOnClickedOutside -->
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateCustomSearchWithoutEndDate" time="22.986"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateCustomSearchWithoutStartDate" time="28.352"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateLoanBalanceAmountsVisibility" time="28.987"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateFacilitiesBalanceAmountsVisibility" time="23.838"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateCashBalanceSectionsVisibility" time="21.024"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateCurrentCashAmount" time="22.771">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at com.Reporting.tests.BalanceSheetTest.validateCurrentCashAmount(BalanceSheetTest.java:6592)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- validateCurrentCashAmount -->
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateCashBalanceTableColumnsVisibility" time="20.169"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateCashBalanceColumn" time="21.220"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validatePaymentAndReceiptColumns" time="21.227"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateCashBalanceForReceipt" time="136.988"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateCashBalanceForPayments" time="90.403"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateSortingOfCashBalanceTable" time="33.559"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateCashBalanceValueInTopRowOfCashBalanceTable" time="20.033">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at com.Reporting.tests.BalanceSheetTest.validateCashBalanceValueInTopRowOfCashBalanceTable(BalanceSheetTest.java:7243)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- validateCashBalanceValueInTopRowOfCashBalanceTable -->
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateLoanAccountSectionsVisibility" time="13.931"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateCurrentLoanBalance" time="18.740"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateLoanAccountTabTableColumns" time="33.672"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateDefaultSortOrderOfCashBalanceTable" time="17.907"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateLoanBalanceAmount" time="16.776"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateLoanBalanceValueInTopRowOfCashBalanceTable" time="23.649">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at com.Reporting.tests.BalanceSheetTest.validateLoanBalanceValueInTopRowOfCashBalanceTable(BalanceSheetTest.java:7735)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- validateLoanBalanceValueInTopRowOfCashBalanceTable -->
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateFundingAccountSectionsVisibility" time="12.590"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateCurrentAllocatedAmount" time="18.871"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateFundingAccountTabTableColumns" time="18.293"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateReverseChronologicalOrderOfCashBalanceTable" time="32.390"/>
  <system-out/>
  <testcase classname="com.Reporting.tests.BalanceSheetTest" name="validateAllocatedAmountValueInTopRowOfCashBalanceTable" time="19.196">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at com.Reporting.tests.BalanceSheetTest.validateAllocatedAmountValueInTopRowOfCashBalanceTable(BalanceSheetTest.java:8160)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- validateAllocatedAmountValueInTopRowOfCashBalanceTable -->
  <system-out/>
</testsuite> <!-- com.Reporting.tests.BalanceSheetTest -->
